routes/web.php
<?php

use App\Http\Controllers\ClienteController;
use App\Http\Controllers\TransactionController;
use App\http\Controllers\ReporteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return redirect()->route('operaciones.index');
});

Route::get('/menu', function () {
    return view('front.pages.menu');
})->name('menu');

Route::group(["prefix"=>'reportes','as'=>'reportes.'],function(){
    Route::get('/',[ReporteController::class,'index'])->name('index');
});

Route::group(["prefix"=>'clientes','as'=>'clientes.'],function(){
    Route::get('/',[ClienteController::class,'index'])->name('index');
});

Route::group(["prefix"=>'operaciones','as'=>'operaciones.'],function(){
    Route::get('/',[TransactionController::class,'index'])->name('index');
    Route::match(["get","post"],'/validar-tarjeta/{tarjeta?}/{fallos?}',[TransactionController::class,'validarTarjeta'])->name('validar-tarjeta');
    Route::match(["get","post"],'/operaciones/{card?}',[TransactionController::class,'showMenuOperaciones'])->name('menu');
    Route::get('/balance/{tarjeta}',[TransactionController::class,'getBalance'])->name('balance');
    Route::get('/retiro/{tarjeta}',[TransactionController::class,'hacerRetiro'])->name('retiro');
    Route::post('/validar-retiro',[TransactionController::class,'validarRetiro'])->name('retiro.validar');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

resources/views/front/pages/cajero/balance.blade.php
@extends('layouts.app')
@section('content')
<div class="grid grid-cols-4 h-full">
    <div class="col-span-3 h-full">
        <form class="h-full" action="{{ route('operaciones.menu') }}" method="POST" onreset="clearvalues()">
            @csrf
            <div class="mx-auto w-11/12 h-1/2 py-4">
                <div class="h-full rounded-lg bg-white shadow-lg flex flex-col justify-center items-center px-5">
                    @if (session()->has('resultado-operacion'))
                    <div class="px-2 py-1 bg-green-200 border-green-700 shadow-lg w-3/4 text-center">
                        <span class="text-green-700 text-lg">{{ session()->get('resultado-operacion') }}</span>
                    </div>
                    @endif
                    {{-- {{ $tarjeta }} --}}
                    @if (session()->has('resultado-operacion'))
                    <table class="w-full">
                        <tr class="h-16">
                            <th class="text-left w-1/3">Nro de Tarjeta</th>
                            <td>{{ $tarjeta->codigo }}</tr>
                        </tr>
                        <tr class="h-16">
                            <th class="text-left w-1/3">Fecha - Hora de la transaccion</th>
                            <td>{{ \Carbon\Carbon::parse($tarjeta->getUltimaOperacion()->fecha)->format('d-m-Y H:i:s') }}</td>
                        </tr>
                        <tr class="h-16">
                            <th class="text-left w-1/3">Monto Retirado</th>
                            <td>{{ number_format($tarjeta->getUltimaOperacion()->monto,2,",",".") }}</td>
                        </tr>
                        <tr class="h-16">
                            <th class="text-left w-1/3">Saldo Disponible</th>
                            <td>{{ number_format($tarjeta->cuenta->saldo,2,",",".") }}</td>
                        </tr>
                    </table>
                    @else
                    <table class="w-full">
                        <tr class="h-16">
                            <th class="text-left w-1/3">Nro de Tarjeta</th>
                            <td>{{ $tarjeta->codigo }}</tr>
                        </tr>
                        <tr class="h-16">
                            <th class="text-left w-1/3">Fecha Vencimiento</th>
                            <td>{{ \Carbon\Carbon::parse($tarjeta->expiracion)->format('Y/m') }}</td>
                        </tr>
                        <tr class="h-16">
                            <th class="text-left w-1/3">Saldo Disponible</th>
                            <td>{{ number_format($tarjeta->cuenta->saldo,2,",",".") }}</td>
                        </tr>
                    </table>
                    @endif
                </div>
            </div>
            <div class="mx-auto w-11/12 grid grid-cols-6 gap-4 py-5 h-2/5">
                <div class="col-span-6 grid grid-cols-6 gap-4">
                    @foreach (range(1, 9) as $item)
                        <input type="button"
                            class="col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                            onclick="validateCardNumber(event,this)" value="{{ $item }}" />
                    @endforeach

                    <input type="button" wire:click="$emitUp('validarTarjeta',0)"
                        class="col-start-3 col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                        value="0" onclick="validateCardNumber(event,this)">
                </div>
            </div>
        </form>
    </div>
    <div class="col-span-1 h-full flex flex-col justify-center items-center gap-y-5">
        <a href="{{ route('operaciones.menu',$tarjeta->id) }}" class="w-36 text-center px-5 py-3 bg-gray-800 text-white rounded-lg shadow-lg hover:shadow-inner">Atras</a>
        <a href="{{ route('operaciones.index') }}" class="w-36 text-center px-5 py-3 bg-gray-800 text-white rounded-lg shadow-lg hover:shadow-inner">Salir</a>
    </div>
</div>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js?{{ substr(microtime(), -5) }}"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js?{{ substr(microtime(), -5) }}">
    </script>
    <script>
        $(document).ready(function() {
            $('#cardnumber').mask('####-####-####-####');
        });

        let ping = "";
        function validateCardNumber(event, elemento) {
            ping+= elemento.value;
            if(ping.length <=4)
            {
                document.querySelector("#ping").value = ping;
                if(ping.length ===16) wire:{
                    document.querySelector("#btn_aceptar").classList.remove('bg-green-300');
                    document.querySelector("#btn_aceptar").classList.add('bg-green-600');
                    document.querySelector("#btn_aceptar").disabled = false;
                }
            }
        }

        function clearvalues(){
            ping = "";
        }


        function maskify(cardcode){
            aux = cardcode.split('');

            if(aux.length %4 == 0)
            {
                if(cardcode.length == 4) aux.splice(aux.length,0,'-');
                if(cardcode.length == 8) {
                    aux.splice(4,0,'-');
                    aux.splice(aux.length,0,'-');
                }
                if(cardcode.length == 12) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(aux.length,0,'-');
                }

                if(cardcode.length == 16) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(14,0,'-');
                }

            }
            return aux.join('');
        }
    </script>
@endpush

resources/views/front/pages/cajero/index.blade.php
@extends('layouts.app')
@section('content')
    <form class="h-full" action="{{ route('operaciones.validar-tarjeta') }}" method="POST" onreset="clearvalues()">
        @csrf
        <div class="mx-auto w-5/6 h-1/2 py-4">
            <div class="h-full rounded-lg bg-white shadow-lg flex flex-col justify-center items-center px-5">
                {{-- {{ $tarjeta }} --}}
                <label class="font-semibold w-5/6">Indique su número de tarjeta</label>
                <div class="w-5/6">
                    <input type="hidden" id="cardcode" name="codigo" maxlength="16">
                    <input type="text" id="cardnumber" name="cardnumber" maxlength="19"
                        class="rounded-xl w-full py-8 text-3xl" data-mask="####-####-####-####"
                        data-mask-clearifnotmatch="true">
                    @if (session()->has('error-card-code'))
                        <span class="text-red-700 text-xl">{{ session()->get('error-card-code') }}</span>
                    @endif
                </div>
            </div>
        </div>
        <div class="mx-auto w-5/6 grid grid-cols-6 gap-4 py-5 h-2/5">
            @foreach (range(1, 9) as $item)
                <input type="button"
                    class="col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                    onclick="validateCardNumber(event,this)" value="{{ $item }}" />
            @endforeach
            <input type="reset" wire:click="$emitUp('limpiar')"
                class="col-span-2 bg-red-400 text-white  h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                value="Limpiar">
            <input type="button" wire:click="$emitUp('validarTarjeta',0)"
                class="col-start-3 col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                value="0" onclick="validateCardNumber(event,this)">
            <input type="submit" id="btn_aceptar" disabled="disabled"
                class="col-span-2 bg-green-300 text-white  h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                value="Aceptar">
        </div>
    </form>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js?{{ substr(microtime(), -5) }}"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js?{{ substr(microtime(), -5) }}">
    </script>
    <script>
        $(document).ready(function() {
            $('#cardnumber').mask('####-####-####-####');
        });

        let card = "";
        function validateCardNumber(event, elemento) {
            card+= elemento.value;
            if(card.length <=16)
            {
                document.querySelector("#cardcode").value = card;
                document.querySelector("#cardnumber").value = maskify(card);
                if(card.length ===16) wire:{
                    document.querySelector("#btn_aceptar").classList.remove('bg-green-300');
                    document.querySelector("#btn_aceptar").classList.add('bg-green-600');
                    document.querySelector("#btn_aceptar").disabled = false;
                }
            }
        }

        function clearvalues(){
            card = "";
        }


        function maskify(cardcode){
            aux = cardcode.split('');

            if(aux.length %4 == 0)
            {
                if(cardcode.length == 4) aux.splice(aux.length,0,'-');
                if(cardcode.length == 8) {
                    aux.splice(4,0,'-');
                    aux.splice(aux.length,0,'-');
                }
                if(cardcode.length == 12) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(aux.length,0,'-');
                }

                if(cardcode.length == 16) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(14,0,'-');
                }

            }
            return aux.join('');
        }
    </script>
@endpush

resources/views/front/pages/cajero/menu-operacion.blade.php
@extends('layouts.app')
@section('content')
<div class="grid grid-cols-4 h-full">
    <div class="col-span-3 h-full">
        <form class="h-full" action="{{ route('operaciones.menu') }}" method="POST" onreset="clearvalues()">
            @csrf
            <div class="mx-auto w-11/12 h-1/2 py-4">
                <div class="h-full rounded-lg bg-white shadow-lg flex flex-col justify-center items-center px-5">
                    {{-- {{ $tarjeta }} --}}
                    <label class="font-semibold w-5/6">Seleccione una operación el menú</label>
                    <div class="w-5/6">
                        <input type="hidden" id="tarjeta" name="tarjeta" value="{{ $tarjeta->id }}">
                        <input type="password" id="ping" name="ping" maxlength="4"
                            class="sr-only rounded-xl w-full py-8 text-3xl text-center" data-mask="####-####-####-####"
                            data-mask-clearifnotmatch="true">
                        @if (session()->has('error-card-code'))
                            <span class="text-red-700 text-xl">{{ session()->get('error-card-code') }}</span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="mx-auto w-11/12 grid grid-cols-6 gap-4 py-5 h-2/5">
                <div class="col-span-6 grid grid-cols-6 gap-4">
                    @foreach (range(1, 9) as $item)
                        <input type="button"
                            class="col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-100 hover:text-white"
                            disabled onclick="validateCardNumber(event,this)" value="{{ $item }}" />
                    @endforeach

                    <input type="button" wire:click="$emitUp('validarTarjeta',0)"
                        class="col-start-3 col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-100 hover:text-white"
                        value="0" disabled onclick="validateCardNumber(event,this)">
                </div>
            </div>
        </form>
    </div>
    <div class="col-span-1 h-full flex flex-col justify-center items-center gap-y-5">
            <a href="{{ route('operaciones.balance',$tarjeta->id) }}" class="w-36 text-center px-5 py-3 bg-gray-800 text-white rounded-lg shadow-lg hover:shadow-inner">Balance</a>
            <a href="{{ route('operaciones.retiro',$tarjeta->id) }}" class="w-36 text-center px-5 py-3 bg-gray-800 text-white rounded-lg shadow-lg hover:shadow-inner">Retiro</a>
            <a href="" class="w-36 text-center px-5 py-3 bg-gray-800 text-white rounded-lg shadow-lg hover:shadow-inner">Salir</a>
    </div>
</div>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js?{{ substr(microtime(), -5) }}"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js?{{ substr(microtime(), -5) }}">
    </script>
    <script>
        $(document).ready(function() {
            $('#cardnumber').mask('####-####-####-####');
        });

        let ping = "";
        function validateCardNumber(event, elemento) {
            ping+= elemento.value;
            if(ping.length <=4)
            {
                document.querySelector("#ping").value = ping;
                if(ping.length ===16) wire:{
                    document.querySelector("#btn_aceptar").classList.remove('bg-green-300');
                    document.querySelector("#btn_aceptar").classList.add('bg-green-600');
                    document.querySelector("#btn_aceptar").disabled = false;
                }
            }
        }

        function clearvalues(){
            ping = "";
        }


        function maskify(cardcode){
            aux = cardcode.split('');

            if(aux.length %4 == 0)
            {
                if(cardcode.length == 4) aux.splice(aux.length,0,'-');
                if(cardcode.length == 8) {
                    aux.splice(4,0,'-');
                    aux.splice(aux.length,0,'-');
                }
                if(cardcode.length == 12) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(aux.length,0,'-');
                }

                if(cardcode.length == 16) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(14,0,'-');
                }

            }
            return aux.join('');
        }
    </script>
@endpush

resources/views/front/pages/cajero/ping.blade.php
@extends('layouts.app')
@section('content')
    <form class="h-full" action="{{ route('operaciones.menu') }}" method="POST" onreset="clearvalues()">
        @csrf
        <div class="mx-auto w-5/6 h-1/2 py-4">
            <div class="h-full rounded-lg bg-white shadow-lg flex flex-col justify-center items-center px-5">
                {{-- {{ $tarjeta }} --}}
                <label class="font-semibold w-5/6">Marque su clave Secreta</label>
                <div class="w-5/6">
                    <input type="hidden" id="tarjeta" name="tarjeta" value="{{ $tarjeta->id }}">
                    <input type="password" id="ping" name="ping" maxlength="4"
                        class="rounded-xl w-full py-8 text-3xl text-center" data-mask="####-####-####-####"
                        data-mask-clearifnotmatch="true">
                    @if (session()->has('error-card-code'))
                        <span class="text-red-700 text-xl">{{ session()->get('error-card-code') }}</span>
                    @endif
                </div>
            </div>
        </div>
        <div class="mx-auto w-5/6 grid grid-cols-6 gap-4 py-5 h-2/5">
            <div class="col-span-5 grid grid-cols-6 gap-4">
                @foreach (range(1, 9) as $item)
                    <input type="button"
                        class="col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                        onclick="validateCardNumber(event,this)" value="{{ $item }}" />
                @endforeach

                <input type="button" wire:click="$emitUp('validarTarjeta',0)"
                    class="col-start-3 col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                    value="0" onclick="validateCardNumber(event,this)">
            </div>
            <div class="col-span-1 h-full flex flex-col justify-center items-center">
                <div class="grid grid-cols-1 gap-y-5">
                    <input type="button" wire:click="$emitUp('limpiar')"
                        class="bg-red-400 text-white  px-2 py-1 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                        value="Cancelar">
                    <input type="reset" wire:click="$emitUp('limpiar')"
                        class="bg-yellow-400 text-white  px-2 py-1 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                        value="Limpiar">
                        <input type="submit" id="btn_aceptar"
                        class="bg-green-400 text-white  px-2 py-1 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                        value="Aceptar">
                </div>
            </div>
        </div>
    </form>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js?{{ substr(microtime(), -5) }}"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js?{{ substr(microtime(), -5) }}">
    </script>
    <script>
        $(document).ready(function() {
            $('#cardnumber').mask('####-####-####-####');
        });

        let ping = "";
        function validateCardNumber(event, elemento) {
            ping+= elemento.value;
            if(ping.length <=4)
            {
                document.querySelector("#ping").value = ping;
                if(ping.length ===16) wire:{
                    document.querySelector("#btn_aceptar").classList.remove('bg-green-300');
                    document.querySelector("#btn_aceptar").classList.add('bg-green-600');
                    document.querySelector("#btn_aceptar").disabled = false;
                }
            }
        }

        function clearvalues(){
            ping = "";
        }


        function maskify(cardcode){
            aux = cardcode.split('');

            if(aux.length %4 == 0)
            {
                if(cardcode.length == 4) aux.splice(aux.length,0,'-');
                if(cardcode.length == 8) {
                    aux.splice(4,0,'-');
                    aux.splice(aux.length,0,'-');
                }
                if(cardcode.length == 12) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(aux.length,0,'-');
                }

                if(cardcode.length == 16) {
                    aux.splice(4,0,'-');
                    aux.splice(9,0,'-');
                    aux.splice(14,0,'-');
                }

            }
            return aux.join('');
        }
    </script>
@endpush

resources/views/front/pages/cajero/retiro.blade.php
@extends('layouts.app')
@section('content')
    <form class="h-full" action="{{ route('operaciones.retiro.validar') }}" method="POST" onreset="clearvalues()">
        @csrf
        <div class="mx-auto w-5/6 h-1/2 py-4">
            <div class="h-full rounded-lg bg-white shadow-lg flex flex-col justify-center items-center px-5">
                {{-- {{ $tarjeta }} --}}
                <label class="font-semibold w-5/6">Ingrese el Monto</label>
                <div class="w-5/6">
                    <input type="hidden" id="tarjeta" name="tarjeta" value="{{ $tarjeta->id }}">
                    <input type="text" id="monto" name="monto" maxlength="{{ strlen(intval($tarjeta->cuenta->saldo)) }}"
                        class="rounded-xl w-full py-8 text-3xl text-center" data-mask="####-####-####-####"
                        data-mask-clearifnotmatch="true">
                    @if (session()->has('error-retiro'))
                        <span class="text-red-700 text-xl">{{ session()->get('error-retiro') }}</span>
                    @endif
                </div>
            </div>
        </div>
        <div class="mx-auto w-5/6 grid grid-cols-6 gap-4 py-5 h-2/5">
            <div class="col-span-5 grid grid-cols-6 gap-4">
                @foreach (range(1, 9) as $item)
                    <input type="button"
                        class="col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                        onclick="ingresarMonto(event,this)" value="{{ $item }}" />
                @endforeach

                <input type="button" wire:click="$emitUp('validarTarjeta',0)"
                    class="col-start-3 col-span-2 bg-gray-300 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer hover:bg-gray-900 hover:text-white"
                    value="0" onclick="ingresarMonto(event,this)">
            </div>
            <div class="col-span-1 h-full flex flex-col justify-center items-center">
                <div class="grid grid-cols-1 gap-y-5">
                    <input type="button" wire:click="$emitUp('limpiar')"
                        class="bg-red-400 text-white  px-2 py-1 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                        value="Cancelar">
                    <input type="reset" wire:click="$emitUp('limpiar')"
                        class="bg-yellow-400 text-white  px-2 py-1 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                        value="Limpiar">
                        <input type="submit" id="btn_aceptar"
                        class="bg-green-400 text-white  px-2 py-1 h-10 rounded-lg shadow-lg hover:shadow-inner hover:cursor-pointer"
                        value="Aceptar">
                </div>
            </div>
        </div>
    </form>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.6.0.min.js?{{ substr(microtime(), -5) }}"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js?{{ substr(microtime(), -5) }}">
    </script>
    <script>
        $(document).ready(function() {
            $('#cardnumber').mask('####-####-####-####');
        });

        let monto = "";
        function ingresarMonto(event, elemento) {
            if(monto.length < document.querySelector("#monto").getAttribute('maxlength'))
            {
                monto+=elemento.value;
                 document.querySelector("#monto").value = monto;
            }
        }

        function clearvalues(){
            monto = "";
        }

    </script>
@endpush